[project]
name = "lesson3-assignment"
version = "0.1.0"
description = " Car Dtataset cleaning"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas>=2.3.2",
    "numpy>=2.3.2",
    "standardscaler>=0.5",
    "scikit-learn 1.3.3",
]


